server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    #是否需要开启自我保护模式
    enableSelfPreservation: false
    #是否使用只读的response-cache
    use-read-only-response-cache: false
    response-cache-auto-expiration-in-seconds: 10

spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

management:
  endpoints:
    web:
      exposure:
        include: '*'